//! Cell-list neighbor search for non-bonded interactions.

use md_core::{CoreError, SimulationBox, SystemState};
use thiserror::Error;

/// Boundary handling for neighbor search.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum NeighborBoundary {
    Open,
    Periodic(SimulationBox),
}

impl NeighborBoundary {
    fn displacement(&self, dx: f64, dy: f64, dz: f64) -> (f64, f64, f64) {
        match self {
            Self::Open => (dx, dy, dz),
            Self::Periodic(simulation_box) => simulation_box.minimum_image_delta(dx, dy, dz),
        }
    }
}

/// Configuration for a Verlet-style neighbor list.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct NeighborListConfig {
    pub cutoff: f64,
    pub skin: f64,
    pub boundary: NeighborBoundary,
}

impl NeighborListConfig {
    pub fn list_cutoff(&self) -> f64 {
        self.cutoff + self.skin
    }

    pub fn validate(&self) -> Result<(), NeighborError> {
        if !self.cutoff.is_finite() || self.cutoff <= 0.0 {
            return Err(NeighborError::InvalidParameter {
                name: "cutoff",
                value: self.cutoff,
            });
        }
        if !self.skin.is_finite() || self.skin < 0.0 {
            return Err(NeighborError::InvalidParameter {
                name: "skin",
                value: self.skin,
            });
        }

        if let NeighborBoundary::Periodic(simulation_box) = self.boundary {
            simulation_box.validate()?;
            let max_list_cutoff = 0.5 * simulation_box.min_dimension();
            if self.list_cutoff() > max_list_cutoff {
                return Err(NeighborError::ListCutoffTooLargeForPeriodicBox {
                    list_cutoff: self.list_cutoff(),
                    max_list_cutoff,
                });
            }
        }

        Ok(())
    }
}

/// Verlet neighbor list generated by a cell list.
#[derive(Debug, Clone, PartialEq)]
pub struct NeighborList {
    config: NeighborListConfig,
    pairs: Vec<(usize, usize)>,
    reference_x: Vec<f64>,
    reference_y: Vec<f64>,
    reference_z: Vec<f64>,
    cell_count: [usize; 3],
    rebuild_count: usize,
}

impl NeighborList {
    pub fn build(system: &SystemState, config: NeighborListConfig) -> Result<Self, NeighborError> {
        config.validate()?;
        system.validate()?;

        let cell_list = CellList::build(system, &config)?;
        let mut pairs = collect_pairs(system, &config, &cell_list);
        pairs.sort_unstable();
        pairs.dedup();

        Ok(Self {
            config,
            pairs,
            reference_x: system.x.clone(),
            reference_y: system.y.clone(),
            reference_z: system.z.clone(),
            cell_count: cell_list.cell_count,
            rebuild_count: 1,
        })
    }

    pub fn rebuild(&mut self, system: &SystemState) -> Result<(), NeighborError> {
        let rebuilt = Self::build(system, self.config)?;
        self.pairs = rebuilt.pairs;
        self.reference_x = rebuilt.reference_x;
        self.reference_y = rebuilt.reference_y;
        self.reference_z = rebuilt.reference_z;
        self.cell_count = rebuilt.cell_count;
        self.rebuild_count += 1;
        Ok(())
    }

    pub fn needs_rebuild(&self, system: &SystemState) -> Result<bool, NeighborError> {
        system.validate()?;
        if system.particle_count() != self.reference_x.len() {
            return Err(NeighborError::ParticleCountChanged {
                expected: self.reference_x.len(),
                actual: system.particle_count(),
            });
        }

        let threshold_sq = 0.25 * self.config.skin * self.config.skin;
        for i in 0..system.particle_count() {
            let dx = system.x[i] - self.reference_x[i];
            let dy = system.y[i] - self.reference_y[i];
            let dz = system.z[i] - self.reference_z[i];
            let (dx, dy, dz) = self.config.boundary.displacement(dx, dy, dz);
            let displacement_sq = dx * dx + dy * dy + dz * dz;
            if displacement_sq > threshold_sq {
                return Ok(true);
            }
        }

        Ok(false)
    }

    pub fn pairs(&self) -> &[(usize, usize)] {
        &self.pairs
    }

    pub fn config(&self) -> NeighborListConfig {
        self.config
    }

    pub fn particle_count(&self) -> usize {
        self.reference_x.len()
    }

    pub fn cell_count(&self) -> [usize; 3] {
        self.cell_count
    }

    pub fn rebuild_count(&self) -> usize {
        self.rebuild_count
    }
}

#[derive(Debug, Clone, PartialEq)]
struct CellList {
    cells: Vec<Vec<usize>>,
    cell_count: [usize; 3],
    lower: [f64; 3],
    cell_size: [f64; 3],
}

impl CellList {
    fn build(system: &SystemState, config: &NeighborListConfig) -> Result<Self, NeighborError> {
        let bounds = CellBounds::from_system(system, config)?;
        let cell_total = bounds.cell_count[0] * bounds.cell_count[1] * bounds.cell_count[2];
        let mut cell_list = Self {
            cells: vec![Vec::new(); cell_total],
            cell_count: bounds.cell_count,
            lower: bounds.lower,
            cell_size: bounds.cell_size,
        };

        for particle in 0..system.particle_count() {
            let cell = cell_list.cell_for_particle(system, particle, config.boundary);
            let index = cell_list.flatten(cell);
            cell_list.cells[index].push(particle);
        }

        Ok(cell_list)
    }

    fn cell_for_particle(
        &self,
        system: &SystemState,
        particle: usize,
        boundary: NeighborBoundary,
    ) -> [usize; 3] {
        let mut x = system.x[particle];
        let mut y = system.y[particle];
        let mut z = system.z[particle];

        if let NeighborBoundary::Periodic(simulation_box) = boundary {
            simulation_box.wrap_position(&mut x, &mut y, &mut z);
        }

        [
            self.component_cell(x, 0),
            self.component_cell(y, 1),
            self.component_cell(z, 2),
        ]
    }

    fn component_cell(&self, value: f64, dimension: usize) -> usize {
        let raw = ((value - self.lower[dimension]) / self.cell_size[dimension]).floor();
        let upper = self.cell_count[dimension].saturating_sub(1) as f64;
        raw.clamp(0.0, upper) as usize
    }

    fn flatten(&self, cell: [usize; 3]) -> usize {
        (cell[2] * self.cell_count[1] + cell[1]) * self.cell_count[0] + cell[0]
    }

    fn unflatten(&self, index: usize) -> [usize; 3] {
        let nx = self.cell_count[0];
        let ny = self.cell_count[1];
        let z = index / (nx * ny);
        let remainder = index % (nx * ny);
        let y = remainder / nx;
        let x = remainder % nx;
        [x, y, z]
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
struct CellBounds {
    cell_count: [usize; 3],
    lower: [f64; 3],
    cell_size: [f64; 3],
}

impl CellBounds {
    fn from_system(
        system: &SystemState,
        config: &NeighborListConfig,
    ) -> Result<Self, NeighborError> {
        match config.boundary {
            NeighborBoundary::Periodic(simulation_box) => {
                let list_cutoff = config.list_cutoff();
                let cell_count = [
                    periodic_cell_count(simulation_box.x, list_cutoff),
                    periodic_cell_count(simulation_box.y, list_cutoff),
                    periodic_cell_count(simulation_box.z, list_cutoff),
                ];
                Ok(Self {
                    cell_count,
                    lower: [0.0, 0.0, 0.0],
                    cell_size: [
                        simulation_box.x / cell_count[0] as f64,
                        simulation_box.y / cell_count[1] as f64,
                        simulation_box.z / cell_count[2] as f64,
                    ],
                })
            }
            NeighborBoundary::Open => {
                let (min, max) = open_bounds(system);
                let list_cutoff = config.list_cutoff();
                let span = [
                    (max[0] - min[0]).max(list_cutoff),
                    (max[1] - min[1]).max(list_cutoff),
                    (max[2] - min[2]).max(list_cutoff),
                ];
                let cell_count = [
                    open_cell_count(span[0], list_cutoff),
                    open_cell_count(span[1], list_cutoff),
                    open_cell_count(span[2], list_cutoff),
                ];
                Ok(Self {
                    cell_count,
                    lower: min,
                    cell_size: [
                        span[0] / cell_count[0] as f64,
                        span[1] / cell_count[1] as f64,
                        span[2] / cell_count[2] as f64,
                    ],
                })
            }
        }
    }
}

fn periodic_cell_count(length: f64, list_cutoff: f64) -> usize {
    (length / list_cutoff).floor().max(1.0) as usize
}

fn open_cell_count(span: f64, list_cutoff: f64) -> usize {
    (span / list_cutoff).floor().max(1.0) as usize
}

fn open_bounds(system: &SystemState) -> ([f64; 3], [f64; 3]) {
    let mut min = [f64::INFINITY; 3];
    let mut max = [f64::NEG_INFINITY; 3];

    for i in 0..system.particle_count() {
        min[0] = min[0].min(system.x[i]);
        min[1] = min[1].min(system.y[i]);
        min[2] = min[2].min(system.z[i]);
        max[0] = max[0].max(system.x[i]);
        max[1] = max[1].max(system.y[i]);
        max[2] = max[2].max(system.z[i]);
    }

    if system.particle_count() == 0 {
        ([0.0, 0.0, 0.0], [1.0, 1.0, 1.0])
    } else {
        (min, max)
    }
}

fn collect_pairs(
    system: &SystemState,
    config: &NeighborListConfig,
    cell_list: &CellList,
) -> Vec<(usize, usize)> {
    let list_cutoff_sq = config.list_cutoff() * config.list_cutoff();
    let mut pairs = Vec::new();

    for cell_index in 0..cell_list.cells.len() {
        let cell = cell_list.unflatten(cell_index);
        for neighbor_cell in neighbor_cells(cell, cell_list.cell_count, config.boundary) {
            let neighbor_index = cell_list.flatten(neighbor_cell);
            for &i in &cell_list.cells[cell_index] {
                for &j in &cell_list.cells[neighbor_index] {
                    if i >= j {
                        continue;
                    }

                    let dx = system.x[i] - system.x[j];
                    let dy = system.y[i] - system.y[j];
                    let dz = system.z[i] - system.z[j];
                    let (dx, dy, dz) = config.boundary.displacement(dx, dy, dz);
                    let r_sq = dx * dx + dy * dy + dz * dz;
                    if r_sq <= list_cutoff_sq {
                        pairs.push((i, j));
                    }
                }
            }
        }
    }

    pairs
}

fn neighbor_cells(
    cell: [usize; 3],
    cell_count: [usize; 3],
    boundary: NeighborBoundary,
) -> Vec<[usize; 3]> {
    let mut cells = Vec::with_capacity(27);
    for dz in -1..=1 {
        for dy in -1..=1 {
            for dx in -1..=1 {
                let Some(x) = neighbor_component(cell[0], dx, cell_count[0], boundary) else {
                    continue;
                };
                let Some(y) = neighbor_component(cell[1], dy, cell_count[1], boundary) else {
                    continue;
                };
                let Some(z) = neighbor_component(cell[2], dz, cell_count[2], boundary) else {
                    continue;
                };
                cells.push([x, y, z]);
            }
        }
    }
    cells
}

fn neighbor_component(
    value: usize,
    delta: isize,
    count: usize,
    boundary: NeighborBoundary,
) -> Option<usize> {
    let raw = value as isize + delta;
    match boundary {
        NeighborBoundary::Open => {
            if raw < 0 || raw >= count as isize {
                None
            } else {
                Some(raw as usize)
            }
        }
        NeighborBoundary::Periodic(_) => Some(raw.rem_euclid(count as isize) as usize),
    }
}

#[derive(Debug, Error)]
pub enum NeighborError {
    #[error(transparent)]
    Core(#[from] CoreError),
    #[error("{name} must be finite and in its valid range: {value}")]
    InvalidParameter { name: &'static str, value: f64 },
    #[error("neighbor-list cutoff+skin {list_cutoff} exceeds half the shortest box length: {max_list_cutoff}")]
    ListCutoffTooLargeForPeriodicBox {
        list_cutoff: f64,
        max_list_cutoff: f64,
    },
    #[error("particle count changed since neighbor list build: expected {expected}, got {actual}")]
    ParticleCountChanged { expected: usize, actual: usize },
}

#[cfg(test)]
mod tests {
    use super::*;

    fn line_system(positions: &[f64]) -> SystemState {
        let mut state = SystemState::new(positions.len());
        for (i, x) in positions.iter().copied().enumerate() {
            state.x[i] = x;
        }
        state
    }

    #[test]
    fn open_neighbor_list_finds_pairs_within_cutoff_plus_skin() {
        let state = line_system(&[0.0, 1.0, 1.7, 4.0]);
        let config = NeighborListConfig {
            cutoff: 1.0,
            skin: 0.8,
            boundary: NeighborBoundary::Open,
        };

        let neighbor_list = NeighborList::build(&state, config).unwrap();

        assert_eq!(neighbor_list.pairs(), &[(0, 1), (0, 2), (1, 2)]);
        assert!(neighbor_list.cell_count()[0] >= 2);
    }

    #[test]
    fn periodic_neighbor_list_finds_pair_across_boundary() {
        let mut state = SystemState::new(2);
        state.x[0] = 0.2;
        state.x[1] = 9.7;
        let config = NeighborListConfig {
            cutoff: 0.6,
            skin: 0.1,
            boundary: NeighborBoundary::Periodic(SimulationBox::new(10.0, 10.0, 10.0).unwrap()),
        };

        let neighbor_list = NeighborList::build(&state, config).unwrap();

        assert_eq!(neighbor_list.pairs(), &[(0, 1)]);
    }

    #[test]
    fn rebuild_check_uses_half_skin_threshold() {
        let mut state = line_system(&[0.0, 1.0]);
        let config = NeighborListConfig {
            cutoff: 1.0,
            skin: 0.4,
            boundary: NeighborBoundary::Open,
        };
        let neighbor_list = NeighborList::build(&state, config).unwrap();

        state.x[0] = 0.19;
        assert!(!neighbor_list.needs_rebuild(&state).unwrap());

        state.x[0] = 0.21;
        assert!(neighbor_list.needs_rebuild(&state).unwrap());
    }

    #[test]
    fn rebuild_updates_pairs_and_rebuild_count() {
        let mut state = line_system(&[0.0, 3.0]);
        let config = NeighborListConfig {
            cutoff: 1.0,
            skin: 0.2,
            boundary: NeighborBoundary::Open,
        };
        let mut neighbor_list = NeighborList::build(&state, config).unwrap();
        assert!(neighbor_list.pairs().is_empty());
        assert_eq!(neighbor_list.rebuild_count(), 1);

        state.x[1] = 1.1;
        neighbor_list.rebuild(&state).unwrap();

        assert_eq!(neighbor_list.pairs(), &[(0, 1)]);
        assert_eq!(neighbor_list.rebuild_count(), 2);
    }

    #[test]
    fn periodic_list_cutoff_must_fit_half_box() {
        let config = NeighborListConfig {
            cutoff: 2.5,
            skin: 0.6,
            boundary: NeighborBoundary::Periodic(SimulationBox::new(6.0, 6.0, 6.0).unwrap()),
        };

        let error = config.validate().unwrap_err();

        assert!(matches!(
            error,
            NeighborError::ListCutoffTooLargeForPeriodicBox { .. }
        ));
    }
}
