charges = [0.0, 0.0, 0.0, 0.0]

[[bonds]]
i = 0
j = 1
k = 25.0
r0 = 1.2

[[bonds]]
i = 1
j = 2
k = 25.0
r0 = 1.2

[[bonds]]
i = 2
j = 3
k = 20.0
r0 = 1.3416407865

[[angles]]
i = 0
j = 1
k = 2
force_constant = 10.0
theta0 = 1.5707963267948966

[[angles]]
i = 1
j = 2
k = 3
force_constant = 8.0
theta0 = 1.8736811952

[[dihedrals]]
i = 0
j = 1
k = 2
l = 3
force_constant = 0.4
multiplicity = 3
phase = 0.0
